### ISSUE TITLE
发现这个repo是空的，想pr一下

### ISSUE THREAD

**Issue by IvanDart1001** [eggjs/egg-zipkin#1]
评论附上repo链接，请多多指点
https://github.com/IvanDart1001/zipkin-instrumentation-egg

**Comment by popomore** [comment]
会基于 https://github.com/eggjs/egg-opentracing 来实现，所以这里会比较简单

**Comment by popomore** [comment]
https://github.com/eggjs/egg-zipkin/pull/2

**Comment by popomore** [comment]
有兴趣可以看下这个 PR https://github.com/eggjs/egg-opentracing/pull/2
